/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.EventQueue;
import DataAccess.GlobalValueSetter;
import DataAccess.ConfigXML.ConfigFileReadXML;
import DataAccess.OutputRedir;
import Threaded.MultiThreadExec;
import Timer.Timer;
import java.io.File;
import java.io.PrintStream;
import javax.swing.JFileChooser;
import javax.swing.SwingWorker;

/**
 *
 * @author MistyukovE
 */
public class HttpDLMain extends javax.swing.JFrame {
    
    
    /**
     * Creates new form HttpDLMain
     */
    public HttpDLMain() {
        initComponents();
        new ConfigFileReadXML().loadConfigFileReadXML();
         dl_OutPath.setText(GlobalValueSetter.getOutput());
         dl_FilePath.setText(GlobalValueSetter.getFilePath());
    }
   
        
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        statistic = new javax.swing.JLabel();
        dlFileButton = new javax.swing.JButton();
        threads_spinner = new javax.swing.JSpinner();
        out_PathButton = new javax.swing.JButton();
        threadsLabel = new javax.swing.JLabel();
        proxyButton = new javax.swing.JButton();
        dLspeedTexField = new javax.swing.JTextField();
        dlSpeedLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        jScrollStatPane = new javax.swing.JScrollPane();
        dl_OutPut = new javax.swing.JTextArea();
        dl_FilePath = new javax.swing.JTextField();
        dl_OutPath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.gray);
        setResizable(false);

        statistic.setText("Statistics:");

        dlFileButton.setText("Load DL File");
        dlFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlFileButtonActionPerformed(evt);
            }
        });

        threads_spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 16, 1));
        threads_spinner.setValue(1);

        out_PathButton.setText("Out Path");
        out_PathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out_PathButtonActionPerformed(evt);
            }
        });

        threadsLabel.setText("Threads count:");

        proxyButton.setText("Proxy set");
        proxyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxyButtonActionPerformed(evt);
            }
        });

        dLspeedTexField.setText("100m");
        dLspeedTexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dLspeedTexFieldActionPerformed(evt);
            }
        });

        dlSpeedLabel.setText("Download speed (k;m):");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        dl_OutPut.setBackground(new java.awt.Color(240, 240, 240));
        dl_OutPut.setColumns(20);
        dl_OutPut.setRows(5);
        jScrollStatPane.setViewportView(dl_OutPut);

        dl_FilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dl_FilePathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollStatPane)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(statistic)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(dl_OutPath, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(proxyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dlFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(out_PathButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dlSpeedLabel))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(dl_FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                                        .addComponent(threadsLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(threads_spinner)
                                    .addComponent(dLspeedTexField))))
                        .addGap(31, 31, 31))))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlFileButton)
                    .addComponent(dlSpeedLabel)
                    .addComponent(dLspeedTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(threads_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threadsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proxyButton)
                        .addGap(66, 66, 66))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(dl_FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(out_PathButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dl_OutPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(statistic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollStatPane, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void out_PathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out_PathButtonActionPerformed
          dl_OutPath.setText(mGetFilesPath(false));
    }//GEN-LAST:event_out_PathButtonActionPerformed

    private void proxyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyButtonActionPerformed
         EventQueue.invokeLater(() -> new ProxyGUI(this).setVisible(true));
    }//GEN-LAST:event_proxyButtonActionPerformed

    private void dLspeedTexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dLspeedTexFieldActionPerformed
        GlobalValueSetter.setOutput(dLspeedTexField.getText());
    }//GEN-LAST:event_dLspeedTexFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        double startTime = System.currentTimeMillis(); 
        
         GlobalValueSetter.setStreams(threads_spinner.getValue().toString());
         
         GlobalValueSetter.setFilePath(dl_FilePath.getText());
         GlobalValueSetter.setOutput(dl_OutPath.getText());
         
         PrintStream out =new PrintStream (new OutputRedir (dl_OutPut));
         System.setOut(out);
         //System.setErr(out);
         
         
         SwingWorker swg = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                   new MultiThreadExec().runner();
                   
                    System.out.println ("==========Statistics:==========");
                    System.out.println("Program worked: " + new Timer().
                            programWorked(startTime));
                    System.out.println ("Downloaded: " + GlobalValueSetter.
                            getTotalBytes()+ " bytes");
                    System.out.println ("===============================");
                    return null;

                }
            };
         if (!(dl_FilePath.getText().equals(""))
                 && !(dl_OutPath.getText().equals(""))){
         swg.execute();
         }
   
    }//GEN-LAST:event_startButtonActionPerformed

    private void dlFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlFileButtonActionPerformed
         dl_FilePath.setText(mGetFilesPath(true));
    }//GEN-LAST:event_dlFileButtonActionPerformed

    private void dl_FilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dl_FilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dl_FilePathActionPerformed

   private String mGetFilesPath (boolean file) {

        String resultSel = "No Folder Selected";
        String UserDirectory = System.getProperty("user.home");
        JFileChooser fc = new JFileChooser(UserDirectory);
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        if (!file){
        fc.setDialogTitle("Select output folder");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        } else {
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle("Select download list file");
        }
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File SelFolder = fc.getSelectedFile();

            resultSel = SelFolder.toString();
           
        }
        return  resultSel;
    }
   
  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dLspeedTexField;
    private javax.swing.JButton dlFileButton;
    private javax.swing.JLabel dlSpeedLabel;
    private javax.swing.JTextField dl_FilePath;
    private javax.swing.JTextField dl_OutPath;
    private javax.swing.JTextArea dl_OutPut;
    private javax.swing.JScrollPane jScrollStatPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton out_PathButton;
    private javax.swing.JButton proxyButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel statistic;
    private javax.swing.JLabel threadsLabel;
    private javax.swing.JSpinner threads_spinner;
    // End of variables declaration//GEN-END:variables
}
